services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    container_name: flask-app
  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./config/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
  grafana:
    image: grafana/grafana:8.5.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    container_name: grafana
  alertmanager:
    image: prom/alertmanager:v0.23.0
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    container_name: alertmanager
volumes:
  grafana-storage: {}
  alertmanager-data: {}