services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app-1
      - flask-app-2
    container_name: nginx
  flask-app-1:
    build: .
    expose:
      - "5000"
      - "8000"
    container_name: flask-app-1
    volumes:
      - ./logs:/var/log
  flask-app-2:
    build: .
    expose:
      - "5000"
      - "8000"
    container_name: flask-app-2
    volumes:
      - ./logs:/var/log
  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./config/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
  grafana:
    image: grafana/grafana:8.5.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    container_name: grafana
  alertmanager:
    image: prom/alertmanager:v0.23.0
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager:/etc/alertmanager
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    container_name: alertmanager
  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    container_name: loki
  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - ./config/promtail:/etc/promtail
      - ./logs:/var/log
    command:
      - '--config.file=/etc/promtail/promtail-config.yml'
    container_name: promtail
volumes:
  grafana-storage: {}
  alertmanager-data: {}