global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:8000']  # Container name and metrics port

rule_files:
  - /etc/prometheus/rules.yml