global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app-1:5000', 'flask-app-2:5000'] # Container names and metrics ports

rule_files:
  - /etc/prometheus/rules.yml