groups:
- name: flask_app_rules
  rules:
  - alert: HighErrorRate
    expr: rate(error_count_total[5m]) > 0.01
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate for {{ $labels.method }} {{ $labels.endpoint }} exceeds 0.01/sec for 1 minute."