apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  rules.yml: |
    groups:
    - name: example
      rules:
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on Flask app"
          description: "CPU usage exceeds 80% for over 5 minutes."
          runbook_url: "https://github.com/rickhouser/system-prism/wiki/Runbook#highcpuusage"
      - alert: HighErrorRate
        expr: rate(error_count_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on Flask app"
          description: "Error rate exceeds 0.1 errors/sec for 5 minutes."
          runbook_url: "https://github.com/rickhouser/system-prism/wiki/Runbook#higherrorrate"